### ISSUE TITLE
this link  https://gerrit.googlesource.com/git-repo  Is it not working?

### ISSUE THREAD

**Issue by HagonChan** [second-state/wasmedge-seL4#12]
![image](https://github.com/second-state/wasmedge-seL4/assets/77165006/075f69aa-0137-4f0e-b0df-0546bc750ed8)
hello！ please ask this link https://raw.githubusercontent.com/second-state/wasmedge-seL4/main/build.sh 
Is it not working?

**Comment by HagonChan** [comment]
![image](https://github.com/second-state/wasmedge-seL4/assets/77165006/038d2954-af4d-4949-aac5-92b0f99098d4)
this link https://gerrit.googlesource.com/git-repo/ is also not work?   Is there something wrong with my network?
it was wrong when i executed "./build.sh"

**Comment by hydai** [comment]
It seems like you need to jump the wall.

**Comment by HagonChan** [comment]
> It seems like you need to jump the wall.

Thank you! but i have jump the wall to America, and it does not work. Can you guys access this link?

**Comment by hydai** [comment]
We did.

![CleanShot 2024-03-12 at 12 50 25](https://github.com/second-state/wasmedge-seL4/assets/2776756/1d135557-41dc-4074-a7a6-1d2dda669972)

**Comment by HagonChan** [comment]
![image](https://github.com/second-state/wasmedge-seL4/assets/77165006/18b71cf9-a0e7-47ed-b4ad-57550d7533b0)

I can access this link as well, I made a mistake at first, it was this link I couldn't access: https://gerrit.googlesource.com/git-repo Could you  try again?

**Comment by hydai** [comment]
Everything is fine. I believe the only issue is the GFW.

![CleanShot 2024-03-12 at 13 01 39](https://github.com/second-state/wasmedge-seL4/assets/2776756/a5640546-8b04-46a1-bf5d-6122ba7c32d2)

**Comment by HagonChan** [comment]
> Everything is fine. I believe the only issue is the GFW.
> 
> ![CleanShot 2024-03-12 at 13 01 39](https://private-user-images.githubusercontent.com/2776756/311946415-a5640546-8b04-46a1-bf5d-6122ba7c32d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMzI4MjcsIm5iZiI6MTcxMDIzMjUyNywicGF0aCI6Ii8yNzc2NzU2LzMxMTk0NjQxNS1hNTY0MDU0Ni04YjA0LTQ2YTEtYmY1ZC02MTIyYmE3YzMyZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMDgzNTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWQ3YTA0MDMwYzRkZDA2NjFkMmViYjI0YzllOGVkMTJmYWNmN2ZhNGIxMmRmZTVkOGQ2OTQ5YjIxOTdjM2U5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fLMM54evqEud8HA2Fu2cI7VKXxGi8zkaFodQHNm0OfM)

i got it，and i found a mirror to solve this problem！https://github.com/GerritCodeReview/git-repo
