### ISSUE TITLE
 How to send a .wasm file from ubuntu to the guest Linux？

### ISSUE THREAD

**Issue by HagonChan** [second-state/wasmedge-seL4#13]
![83b988debdb7f1ab4e495189e2939f9](https://github.com/second-state/wasmedge-seL4/assets/77165006/66e4b4b4-660f-4612-a0fc-51884314ec60)

it was wrong when i run “./build.sh”,  how to solve this problem?

**Comment by hydai** [comment]
I cannot reproduce your issue.
Using the docker way to build is fine.

**Comment by HagonChan** [comment]
![image](https://github.com/second-state/wasmedge-seL4/assets/77165006/24b1fd2f-2d49-4a3f-98c1-22aeb5ee4415)
in the docker way，[build artifact](https://github.com/second-state/wasmedge-seL4/actions/runs/1374510169)seems not working

**Comment by hydai** [comment]
> ![image](https://private-user-images.githubusercontent.com/77165006/312292543-24b1fd2f-2d49-4a3f-98c1-22aeb5ee4415.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMDIxOTcsIm5iZiI6MTcxMDMwMTg5NywicGF0aCI6Ii83NzE2NTAwNi8zMTIyOTI1NDMtMjRiMWZkMmYtMmQ0OS00YTNmLTk4YzEtMjJhZWI1ZWU0NDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAzNTEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMDg4NzU5MDczMTU3NjZjOWIwNGY3ZThiNGYxZGI1NDExMDYzYmQ0OTc0ZjlkNWM4YzI4ODJiZWVkMzYzNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XWUVUJVwTkb7I3LaNPoqo3TRA6JFmnGL3hfzCRV4T0Q) in the docker way，the link [build artifact](https://github.com/second-state/wasmedge-seL4/actions/runs/1374510169)seems not working

The github action will autoremove the previous log.

**Comment by HagonChan** [comment]
If i want to send a .wasm file from ubuntu to the guest Linux，what should i do？

**Comment by hydai** [comment]
See https://github.com/second-state/wasmedge-seL4/blob/main/build.sh#L52-L53

**Comment by HagonChan** [comment]
> See https://github.com/second-state/wasmedge-seL4/blob/main/build.sh#L52-L53

![image](https://github.com/second-state/wasmedge-seL4/assets/77165006/19a3e37b-d377-450a-8e7f-7a2d533c8b5a)

I have put my .wasm file into the path"/sel4_wasmedge/.repo/manifests/wasm-examples/" or "projects/vm-examples/apps/Arm/wasmedge/overlay_files/".

and i rebuild the project,and simulate. but it did not work

**Comment by hydai** [comment]
And here. https://github.com/second-state/wasmedge-seL4/blob/main/patches/05-vm-examples.patch#L147-L173

**Comment by HagonChan** [comment]
> And here. https://github.com/second-state/wasmedge-seL4/blob/main/patches/05-vm-examples.patch#L147-L173

![image](https://github.com/second-state/wasmedge-seL4/assets/77165006/0eb8d241-b2ef-43e8-8107-16c9e4c3dd7d)

i have edited the .patch file"/home/os/sel4_wasmedge/.repo/manifests/patches/05-vm-examples.patch"  and "/home/os/sel4_wasmedge/kernel/tools/hardware/sel4_wasmedge/.repo/manifests/patches/05-vm-examples.patch".

and i also  put my newHello.wasm file into the path"/sel4_wasmedge/.repo/manifests/wasm-examples/" and "projects/vm-examples/apps/Arm/wasmedge/overlay_files/".

and i rebuild the project,and simulated ,but it still did not work.

**Comment by HagonChan** [comment]
I changed the CMakeLists.txt directly，and added .wasm file to "projects/vm-examples/apps/Arm/wasmedge/overlay_files/"，then it works.
