### ISSUE TITLE
build.sh failed at repo sync

### ISSUE THREAD

**Issue by chairwa** [second-state/wasmedge-seL4#9]
./build.sh

+ .repo/repo/repo sync
error.GitError: Cannot fetch llvm-project.git update-ref: fatal: fa0971b87fb2c9d14d1bba2551e61f02f18f329b^0: not a valid SHA1

Fetching:  4% (1/21) llvm-project.giterror.GitError: Cannot fetch lwip.git update-ref: fatal: 159e31b689577dbf69cf0683bbaffbd71fa5ee10^0: not a valid SHA1

Fetching:  9% (2/21) lwip.giterror.GitError: Cannot fetch camkes-vm-images.git update-ref: fatal: ede9814678d87adfc8d175c743283ea7844ae4ad^0: not a valid SHA1

Fetching: 14% (3/21) camkes-vm-images.giterror.GitError: Cannot fetch camkes-vm.git update-ref: fatal: 0174554598846ac73257bf006250f47a8f73d80c^0: not a valid SHA1

Fetching: 19% (4/21) camkes-vm.giterror.GitError: Cannot fetch camkes-vm-linux.git update-ref: fatal: a9d79657b3f01fabfa2692f815be7276d97c9b85^0: not a valid SHA1

Fetching: 23% (5/21) camkes-vm-linux.giterror.GitError: Cannot fetch camkes-vm-examples.git update-ref: fatal: c5b54ace7a456be493e072111817f65d4ec625b1^0: not a valid SHA1

Fetching: 28% (6/21) camkes-vm-examples.giterror.GitError: Cannot fetch seL4.git update-ref: fatal: eed10507ce62bb4ba5576d1fce79949dcb25494d^0: not a valid SHA1

Fetching: 33% (7/21) seL4.giterror.GitError: Cannot fetch picotcp.git update-ref: fatal: 13c00a067190f5ec62340ed932a2bb833c366d63^0: not a valid SHA1

Fetching: 38% (8/21) picotcp.giterror.GitError: Cannot fetch libzmq update-ref: fatal: d062edd8c142384792955796329baf1e5a3377cd^0: not a valid SHA1

Fetching: 42% (9/21) libzmqerror.GitError: Cannot fetch WasmEdge.git update-ref: fatal: de302010588943679e5154acab3786135744a9eb^0: not a valid SHA1

Fetching: 47% (10/21) WasmEdge.giterror.GitError: Cannot fetch musllibc.git update-ref: fatal: c7aa943a2ad4fccaccf52a1f957bf8860f57f5b0^0: not a valid SHA1

Fetching: 52% (11/21) musllibc.giterror.GitError: Cannot fetch seL4_projects_libs.git update-ref: fatal: 2e30fdeb1d32f1ac252c94b8d6dcf2b9f4ee17b5^0: not a valid SHA1

Fetching: 57% (12/21) seL4_projects_libs.giterror.GitError: Cannot fetch projects_libs.git update-ref: fatal: 3b5c4cdf9e1753c76d0c797cf70c90307714f94d^0: not a valid SHA1

Fetching: 61% (13/21) projects_libs.giterror.GitError: Cannot fetch camkes-tool.git update-ref: fatal: 6528155f1c0bbd551c150283a3b88276d0eafd8b^0: not a valid SHA1

Fetching: 66% (14/21) camkes-tool.giterror.GitError: Cannot fetch capdl.git update-ref: fatal: 5a4d7c85ad3f0201430288475c08ac6ff0e14f07^0: not a valid SHA1

Fetching: 71% (15/21) capdl.giterror.GitError: Cannot fetch global-components.git update-ref: fatal: 02133497ed126910ec0f4ddb98b997e481d91ffa^0: not a valid SHA1

Fetching: 76% (16/21) global-components.giterror.GitError: Cannot fetch seL4_tools.git update-ref: fatal: c09dea9af4908ed0ef05d085ae85eda19dfae5dd^0: not a valid SHA1

Fetching: 80% (17/21) seL4_tools.giterror.GitError: Cannot fetch polly update-ref: fatal: ef7e79c2c297d456f2742fd0b976f555d058d4e0^0: not a valid SHA1

Fetching: 85% (18/21) pollyerror.GitError: Cannot fetch util_libs.git update-ref: fatal: 5f6cec55789f9a0160c427695f600bcf6dd4a1a7^0: not a valid SHA1

Fetching: 90% (19/21) util_libs.giterror.GitError: Cannot fetch seL4_libs update-ref: fatal: 9c0d209d67adda2558db28f5abbae994770d0340^0: not a valid SHA1

Fetching: 95% (20/21) seL4_libserror.GitError: Cannot fetch sel4runtime update-ref: fatal: e1c51c9b506708398bb1ffbf9098ae82855d3c14^0: not a valid SHA1

Fetching: 100% (21/21), done in 30.937s
Garbage collecting: 100% (21/21), done in 0.070s
error.GitError: Cannot fetch seL4.git update-ref: fatal: eed10507ce62bb4ba5576d1fce79949dcb25494d^0: not a valid SHA1

Fetching:  4% (1/21) seL4.giterror.GitError: Cannot fetch camkes-tool.git update-ref: fatal: 6528155f1c0bbd551c150283a3b88276d0eafd8b^0: not a valid SHA1

Fetching:  9% (2/21) camkes-tool.giterror.GitError: Cannot fetch camkes-vm-images.git update-ref: fatal: ede9814678d87adfc8d175c743283ea7844ae4ad^0: not a valid SHA1

Fetching: 14% (3/21) camkes-vm-images.giterror.GitError: Cannot fetch capdl.git update-ref: fatal: 5a4d7c85ad3f0201430288475c08ac6ff0e14f07^0: not a valid SHA1

Fetching: 19% (4/21) capdl.giterror.GitError: Cannot fetch global-components.git update-ref: fatal: 02133497ed126910ec0f4ddb98b997e481d91ffa^0: not a valid SHA1

Fetching: 23% (5/21) global-components.giterror.GitError: Cannot fetch libzmq update-ref: fatal: d062edd8c142384792955796329baf1e5a3377cd^0: not a valid SHA1

Fetching: 28% (6/21) libzmqerror.GitError: Cannot fetch llvm-project.git update-ref: fatal: fa0971b87fb2c9d14d1bba2551e61f02f18f329b^0: not a valid SHA1

Fetching: 33% (7/21) llvm-project.giterror.GitError: Cannot fetch lwip.git update-ref: fatal: 159e31b689577dbf69cf0683bbaffbd71fa5ee10^0: not a valid SHA1

Fetching: 38% (8/21) lwip.giterror.GitError: Cannot fetch musllibc.git update-ref: fatal: c7aa943a2ad4fccaccf52a1f957bf8860f57f5b0^0: not a valid SHA1

Fetching: 42% (9/21) musllibc.giterror.GitError: Cannot fetch picotcp.git update-ref: fatal: 13c00a067190f5ec62340ed932a2bb833c366d63^0: not a valid SHA1

Fetching: 47% (10/21) picotcp.giterror.GitError: Cannot fetch projects_libs.git update-ref: fatal: 3b5c4cdf9e1753c76d0c797cf70c90307714f94d^0: not a valid SHA1

Fetching: 52% (11/21) projects_libs.giterror.GitError: Cannot fetch seL4_libs update-ref: fatal: 9c0d209d67adda2558db28f5abbae994770d0340^0: not a valid SHA1

Fetching: 57% (12/21) seL4_libserror.GitError: Cannot fetch seL4_projects_libs.git update-ref: fatal: 2e30fdeb1d32f1ac252c94b8d6dcf2b9f4ee17b5^0: not a valid SHA1

Fetching: 61% (13/21) seL4_projects_libs.giterror.GitError: Cannot fetch sel4runtime update-ref: fatal: e1c51c9b506708398bb1ffbf9098ae82855d3c14^0: not a valid SHA1

Fetching: 66% (14/21) sel4runtimeerror.GitError: Cannot fetch util_libs.git update-ref: fatal: 5f6cec55789f9a0160c427695f600bcf6dd4a1a7^0: not a valid SHA1

Fetching: 71% (15/21) util_libs.giterror.GitError: Cannot fetch camkes-vm.git update-ref: fatal: 0174554598846ac73257bf006250f47a8f73d80c^0: not a valid SHA1

Fetching: 76% (16/21) camkes-vm.giterror.GitError: Cannot fetch camkes-vm-examples.git update-ref: fatal: c5b54ace7a456be493e072111817f65d4ec625b1^0: not a valid SHA1

Fetching: 80% (17/21) camkes-vm-examples.giterror.GitError: Cannot fetch camkes-vm-linux.git update-ref: fatal: a9d79657b3f01fabfa2692f815be7276d97c9b85^0: not a valid SHA1

Fetching: 85% (18/21) camkes-vm-linux.giterror.GitError: Cannot fetch WasmEdge.git update-ref: fatal: de302010588943679e5154acab3786135744a9eb^0: not a valid SHA1

Fetching: 90% (19/21) WasmEdge.giterror.GitError: Cannot fetch polly update-ref: fatal: ef7e79c2c297d456f2742fd0b976f555d058d4e0^0: not a valid SHA1

Fetching: 95% (20/21) pollyerror.GitError: Cannot fetch seL4_tools.git update-ref: fatal: c09dea9af4908ed0ef05d085ae85eda19dfae5dd^0: not a valid SHA1

Fetching: 100% (21/21), done in 17.301s
Garbage collecting: 100% (21/21), done in 0.139s

error: Unable to fully sync the tree.

**Comment by hydai** [comment]
Looks like these commit hash from upstream are not available now.
We don't have ETA to fix this. But will put it into our to-do list.

**Comment by hydai** [comment]
Hi @chairwa 
We found that is the repo tool issue. And now it is fixed after merged #10
